# Copyright 2025-2026 Hanlian Lu. SPDX-License-Identifier: Apache-2.0
"""Centralized prompts for DlightRAG."""

from .guidance import (
    ANSWER_CITATION_EXAMPLE,
    ANSWER_CONTEXT_GUIDANCE,
    CITATION_GUIDANCE,
    HIGHLIGHT_BATCH_USER_PROMPT,
    HIGHLIGHT_GUIDANCE,
    HIGHLIGHT_RESPONSE_FORMAT,
    LISTWISE_RERANK_PROMPT,
    PLANNER_GUIDANCE,
    RERANK_GUIDANCE,
)
from .identity import CORE_IDENTITY
from .planner import (
    PLANNER_CURRENT_IMAGE_TEMPLATE,
    PLANNER_HISTORY_TEMPLATE,
    PLANNER_NO_HISTORY_TEMPLATE,
    PLANNER_SYSTEM_PROMPT,
    PLANNER_WEB_SELECTION_TEMPLATE,
)
from .rag import (
    ANSWER_CORE,
    HIGHLIGHT_SYSTEM_PROMPT,
    get_answer_system_prompt,
)
from .web_planner import (
    WEB_PLANNER_CURRENT_ATTACHMENT_TEMPLATE,
    WEB_PLANNER_HISTORY_ATTACHMENT_TEMPLATE,
    WEB_PLANNER_SYSTEM_PROMPT,
)

__all__ = [
    # identity
    "CORE_IDENTITY",
    # guidance
    "ANSWER_CONTEXT_GUIDANCE",
    "CITATION_GUIDANCE",
    "ANSWER_CITATION_EXAMPLE",
    "PLANNER_GUIDANCE",
    "RERANK_GUIDANCE",
    "LISTWISE_RERANK_PROMPT",
    "HIGHLIGHT_GUIDANCE",
    "HIGHLIGHT_RESPONSE_FORMAT",
    "HIGHLIGHT_BATCH_USER_PROMPT",
    # planner
    "PLANNER_SYSTEM_PROMPT",
    "PLANNER_HISTORY_TEMPLATE",
    "PLANNER_NO_HISTORY_TEMPLATE",
    "PLANNER_WEB_SELECTION_TEMPLATE",
    "PLANNER_CURRENT_IMAGE_TEMPLATE",
    # web planner
    "WEB_PLANNER_SYSTEM_PROMPT",
    "WEB_PLANNER_HISTORY_ATTACHMENT_TEMPLATE",
    "WEB_PLANNER_CURRENT_ATTACHMENT_TEMPLATE",
    # rag
    "ANSWER_CORE",
    "get_answer_system_prompt",
    "HIGHLIGHT_SYSTEM_PROMPT",
]
