# Copyright 2025-2026 Hanlian Lu. SPDX-License-Identifier: Apache-2.0
"""Centralized prompts for DlightRAG."""

from .guidance import (
    ANSWER_CITATION_EXAMPLE,
    ANSWER_CONTEXT_GUIDANCE,
    CITATION_GUIDANCE,
    HIGHLIGHT_GUIDANCE,
    HIGHLIGHT_RESPONSE_FORMAT,
    HIGHLIGHT_USER_PROMPT,
    LISTWISE_RERANK_PROMPT,
    PLANNER_GUIDANCE,
    RERANK_GUIDANCE,
    VISUAL_RERANK_PROMPT_TEMPLATE,
)
from .identity import CORE_IDENTITY
from .planner import (
    PLANNER_HISTORY_TEMPLATE,
    PLANNER_NO_HISTORY_TEMPLATE,
    PLANNER_SYSTEM_PROMPT,
)
from .rag import (
    ANSWER_CORE,
    HIGHLIGHT_SYSTEM_PROMPT,
    VISUAL_RERANK_PROMPT,
    get_answer_system_prompt,
)

__all__ = [
    # identity
    "CORE_IDENTITY",
    # guidance
    "ANSWER_CONTEXT_GUIDANCE",
    "CITATION_GUIDANCE",
    "ANSWER_CITATION_EXAMPLE",
    "PLANNER_GUIDANCE",
    "RERANK_GUIDANCE",
    "VISUAL_RERANK_PROMPT_TEMPLATE",
    "LISTWISE_RERANK_PROMPT",
    "HIGHLIGHT_GUIDANCE",
    "HIGHLIGHT_RESPONSE_FORMAT",
    "HIGHLIGHT_USER_PROMPT",
    # planner
    "PLANNER_SYSTEM_PROMPT",
    "PLANNER_HISTORY_TEMPLATE",
    "PLANNER_NO_HISTORY_TEMPLATE",
    # rag
    "ANSWER_CORE",
    "get_answer_system_prompt",
    "VISUAL_RERANK_PROMPT",
    "HIGHLIGHT_SYSTEM_PROMPT",
]
