# Copyright 2025-2026 Hanlian Lu. SPDX-License-Identifier: Apache-2.0
"""Durable Web Conversation records, persistence port, and lifecycle."""

from .models import (
    CONVERSATION_HISTORY_PAGE_DEFAULT_LIMIT,
    CONVERSATION_HISTORY_PAGE_MAX_LIMIT,
    CONVERSATION_PAGE_DEFAULT_LIMIT,
    CONVERSATION_PAGE_MAX_LIMIT,
    RECOVERY_PAGE_MAX_LIMIT,
    AnswerTurnCreation,
    CarriedAttachment,
    ConversationCursor,
    ConversationCursorCodec,
    ConversationCursorError,
    ConversationHead,
    ConversationHistoryCursor,
    ConversationHistoryCursorCodec,
    ConversationHistoryPage,
    ConversationHistoryPageRequest,
    ConversationPage,
    ConversationPageRequest,
    ConversationRowPage,
    ConversationSubmissionConflict,
    ConversationSummary,
    LinkedTurn,
    RecoveryPageRequest,
    RecoveryTurnBatch,
    SubmissionSeed,
    WebConversationSchemaError,
    WebConversationStore,
    WebConversationUnavailableError,
)
from .service import WebAnswerSubmission, WebAttachment, WebConversationService

__all__ = [
    "AnswerTurnCreation",
    "CarriedAttachment",
    "CONVERSATION_HISTORY_PAGE_DEFAULT_LIMIT",
    "CONVERSATION_HISTORY_PAGE_MAX_LIMIT",
    "CONVERSATION_PAGE_DEFAULT_LIMIT",
    "CONVERSATION_PAGE_MAX_LIMIT",
    "ConversationCursor",
    "ConversationCursorCodec",
    "ConversationCursorError",
    "ConversationHead",
    "ConversationHistoryCursor",
    "ConversationHistoryCursorCodec",
    "ConversationHistoryPage",
    "ConversationHistoryPageRequest",
    "ConversationPage",
    "ConversationPageRequest",
    "ConversationRowPage",
    "ConversationSubmissionConflict",
    "ConversationSummary",
    "LinkedTurn",
    "RECOVERY_PAGE_MAX_LIMIT",
    "RecoveryPageRequest",
    "RecoveryTurnBatch",
    "SubmissionSeed",
    "WebAnswerSubmission",
    "WebAttachment",
    "WebConversationSchemaError",
    "WebConversationService",
    "WebConversationStore",
    "WebConversationUnavailableError",
]
