# Copyright 2025-2026 Hanlian Lu. SPDX-License-Identifier: Apache-2.0
"""Storage-neutral contracts and coordination for durable work."""

from dlightrag.runtime.contracts import AnswerRunPhase, AnswerRunStatus
from dlightrag.runtime.coordinator import (
    MAINTENANCE_SECONDS,
    RUN_HEARTBEAT_SECONDS,
    SHUTDOWN_WRITE_GRACE_SECONDS,
    SWEEP_SECONDS,
    TOKEN_BATCH_CHARS,
    TOKEN_BATCH_SECONDS,
    DurableWrites,
    LeaseLostError,
    RunCancelledError,
    RunCoordinator,
    RunExecutor,
    RunSession,
)
from dlightrag.runtime.errors import (
    CHECKPOINT_SCHEMA_VERSION,
    MAX_CHECKPOINT_BYTES,
    AnswerRunCancelledError,
    AnswerRunFailedError,
    CheckpointError,
    CheckpointErrorKind,
    RunExecutionError,
    RunSchemaError,
)
from dlightrag.runtime.policy import (
    ANSWER_RUN_LEASE_SECONDS,
    MAX_CONSECUTIVE_RECOVERIES,
    RUN_ABANDONED_ERROR_KIND,
    RUN_RETENTION_SECONDS,
)
from dlightrag.runtime.records import (
    AnswerRunEvent,
    AnswerRunEventType,
    AnswerRunRecord,
    ArtifactAttachOutcome,
    ArtifactReferenceKind,
    CancellationOutcome,
    CheckpointCommit,
    ClaimedRun,
    IdempotencyKeyConflict,
    LeaseRenewal,
    PendingArtifact,
    PendingArtifactReference,
    RunArtifactReference,
    RunCheckpoint,
    RunCreation,
    RunDeletion,
    ShutdownOutcome,
    SweepOutcome,
    TerminalOutcome,
    answer_run_request_fingerprint,
    artifact_digest,
    canonical_run_request_json,
    parse_run_id,
)
from dlightrag.runtime.store import AnswerRunStore
from dlightrag.runtime.subscription import (
    EVENT_POLL_SECONDS,
    EventReader,
    RunEventBroker,
    follow_run_events,
)

__all__ = [
    "ANSWER_RUN_LEASE_SECONDS",
    "AnswerRunEvent",
    "AnswerRunEventType",
    "AnswerRunCancelledError",
    "AnswerRunFailedError",
    "AnswerRunPhase",
    "AnswerRunRecord",
    "AnswerRunStatus",
    "AnswerRunStore",
    "ArtifactAttachOutcome",
    "ArtifactReferenceKind",
    "CancellationOutcome",
    "CheckpointError",
    "CheckpointErrorKind",
    "CheckpointCommit",
    "ClaimedRun",
    "DurableWrites",
    "IdempotencyKeyConflict",
    "LeaseRenewal",
    "LeaseLostError",
    "MAINTENANCE_SECONDS",
    "MAX_CONSECUTIVE_RECOVERIES",
    "PendingArtifact",
    "PendingArtifactReference",
    "RunArtifactReference",
    "RunCheckpoint",
    "RunCreation",
    "RunDeletion",
    "RunCancelledError",
    "RunCoordinator",
    "RunExecutionError",
    "RunSchemaError",
    "RunExecutor",
    "RunEventBroker",
    "RunSession",
    "ShutdownOutcome",
    "SweepOutcome",
    "SWEEP_SECONDS",
    "SHUTDOWN_WRITE_GRACE_SECONDS",
    "TOKEN_BATCH_CHARS",
    "TOKEN_BATCH_SECONDS",
    "TerminalOutcome",
    "answer_run_request_fingerprint",
    "artifact_digest",
    "canonical_run_request_json",
    "parse_run_id",
    "CHECKPOINT_SCHEMA_VERSION",
    "MAX_CHECKPOINT_BYTES",
    "RUN_HEARTBEAT_SECONDS",
    "RUN_ABANDONED_ERROR_KIND",
    "RUN_RETENTION_SECONDS",
    "EVENT_POLL_SECONDS",
    "EventReader",
    "follow_run_events",
]
