// Copyright 2025-2026 Hanlian Lu. SPDX-License-Identifier: Apache-2.0
/** Deterministically project the approved icon selection into a tiny runtime registry. */

import {readFile, writeFile} from 'node:fs/promises';
import {dirname, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

const frontend = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const selectionPath = resolve(frontend, 'design-system/icons/selection.json');
const sourcesPath = resolve(frontend, 'design-system/icons/sources.json');
const nodesPath = resolve(frontend, 'node_modules/lucide-static/icon-nodes.json');
const packagePath = resolve(frontend, 'node_modules/lucide-static/package.json');
const outputPath = resolve(frontend, 'design-system/icons/registry.generated.ts');
const check = process.argv.includes('--check');

const selection = JSON.parse(await readFile(selectionPath, 'utf8'));
const sources = JSON.parse(await readFile(sourcesPath, 'utf8'));
const lucideNodes = JSON.parse(await readFile(nodesPath, 'utf8'));
const lucidePackage = JSON.parse(await readFile(packagePath, 'utf8'));
if (sources.lucide.version !== lucidePackage.version) {
  throw new Error(`Lucide source manifest expects ${sources.lucide.version}, installed ${lucidePackage.version}`);
}
const entries = {};
for (const semanticName of Object.keys(selection).sort()) {
  const selected = selection[semanticName];
  if (!sources[selected.source]) throw new Error(`Missing source metadata for ${selected.source}`);
  const nodes = selected.nodes
    ?? (selected.source === 'lucide' ? lucideNodes[selected.name] : undefined);
  if (!Array.isArray(nodes)) {
    throw new Error(`Missing icon geometry for ${semanticName}: ${selected.source}/${selected.name}`);
  }
  entries[semanticName] = {
    source: selected.source,
    sourceName: selected.name,
    viewBox: selected.viewBox ?? '0 0 24 24',
    opticalScale: selected.opticalScale ?? 1,
    opticalX: selected.opticalX ?? 0,
    opticalY: selected.opticalY ?? 0,
    fill: selected.fill ?? 'none',
    stroke: selected.stroke ?? 'currentColor',
    nodes,
  };
}

const serialized = JSON.stringify(entries, null, 2)
  .replaceAll('"source":', 'source:')
  .replaceAll('"sourceName":', 'sourceName:')
  .replaceAll('"viewBox":', 'viewBox:')
  .replaceAll('"opticalScale":', 'opticalScale:')
  .replaceAll('"opticalX":', 'opticalX:')
  .replaceAll('"opticalY":', 'opticalY:')
  .replaceAll('"fill":', 'fill:')
  .replaceAll('"stroke":', 'stroke:')
  .replaceAll('"nodes":', 'nodes:');
const output = `// Copyright 2025-2026 Hanlian Lu. SPDX-License-Identifier: Apache-2.0
/** GENERATED by scripts/generate_icons.mjs from lucide-static ${lucidePackage.version}. */

export type IconSource = 'lucide' | 'iconoir' | 'phosphor' | 'dlightrag';
export interface IconSourceMetadata {
  readonly license: string;
  readonly url: string;
  readonly package?: string;
  readonly version?: string;
}
export const ICON_SOURCES = ${JSON.stringify(sources, null, 2)} as const satisfies Record<IconSource, IconSourceMetadata>;

export type IconNode = readonly [tag: string, attributes: Readonly<Record<string, string>>];
export interface IconDefinition {
  readonly source: IconSource;
  readonly sourceName: string;
  readonly viewBox: string;
  readonly opticalScale: number;
  readonly opticalX: number;
  readonly opticalY: number;
  readonly fill: string;
  readonly stroke: string;
  readonly nodes: readonly IconNode[];
}

export const ICON_REGISTRY = ${serialized} as const satisfies Record<string, IconDefinition>;
export type IconName = keyof typeof ICON_REGISTRY;
`;

if (check) {
  const current = await readFile(outputPath, 'utf8').catch(() => '');
  if (current !== output) {
    throw new Error('Generated icon registry is stale; run npm run generate:icons');
  }
} else {
  await writeFile(outputPath, output);
}
