# Copyright 2025-2026 Hanlian Lu. SPDX-License-Identifier: Apache-2.0
"""Centralised storage protocols for metadata backends.

MetadataIndexProtocol — interface for structured metadata CRUD + query.
"""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from dlightrag.core.retrieval.models import MetadataFilter


@runtime_checkable
class MetadataIndexProtocol(Protocol):
    """Common interface for PGMetadataIndex and test doubles."""

    async def initialize(self) -> None: ...
    async def upsert(self, doc_id: str, metadata: dict[str, Any]) -> None: ...
    async def get(self, doc_id: str) -> dict[str, Any] | None: ...
    async def get_many(self, doc_ids: list[str]) -> dict[str, dict[str, Any]]: ...
    async def query(self, filters: MetadataFilter) -> list[str]: ...
    async def delete(self, doc_id: str) -> None: ...
    async def clear(self) -> None: ...
    async def find_by_filename(self, name: str) -> list[str]: ...
    async def find_by_file_path(self, file_path: str) -> list[str]: ...
    async def get_field_schema(self) -> dict[str, Any]: ...


__all__ = [
    "MetadataIndexProtocol",
]
