// Copyright 2025-2026 Hanlian Lu. SPDX-License-Identifier: Apache-2.0
/** GENERATED by scripts/generate-icons.mjs from lucide-static 1.38.0. */

export type IconSource = 'lucide' | 'iconoir' | 'phosphor' | 'dlightrag';
export interface IconSourceMetadata {
  readonly license: string;
  readonly url: string;
  readonly package?: string;
  readonly version?: string;
}
export const ICON_SOURCES = {
  "dlightrag": {
    "license": "Apache-2.0",
    "url": "https://github.com/hanlianlyu/DlightRAG"
  },
  "iconoir": {
    "license": "MIT",
    "url": "https://iconoir.com/"
  },
  "lucide": {
    "license": "ISC",
    "package": "lucide-static",
    "version": "1.38.0",
    "url": "https://lucide.dev/"
  },
  "phosphor": {
    "license": "MIT",
    "url": "https://phosphoricons.com/"
  }
} as const satisfies Record<IconSource, IconSourceMetadata>;

export type IconNode = readonly [tag: string, attributes: Readonly<Record<string, string>>];
export interface IconDefinition {
  readonly source: IconSource;
  readonly sourceName: string;
  readonly viewBox: string;
  readonly opticalScale: number;
  readonly opticalX: number;
  readonly opticalY: number;
  readonly fill: string;
  readonly stroke: string;
  readonly nodes: readonly IconNode[];
}

export const ICON_REGISTRY = {
  "add": {
    source: "lucide",
    sourceName: "plus",
    viewBox: "0 0 24 24",
    opticalScale: 1,
    opticalX: 0,
    opticalY: 0,
    fill: "none",
    stroke: "currentColor",
    nodes: [
      [
        "path",
        {
          "d": "M5 12h14"
        }
      ],
      [
        "path",
        {
          "d": "M12 5v14"
        }
      ]
    ]
  },
  "attach": {
    source: "lucide",
    sourceName: "plus",
    viewBox: "0 0 24 24",
    opticalScale: 1,
    opticalX: 0,
    opticalY: 0,
    fill: "none",
    stroke: "currentColor",
    nodes: [
      [
        "path",
        {
          "d": "M5 12h14"
        }
      ],
      [
        "path",
        {
          "d": "M12 5v14"
        }
      ]
    ]
  },
  "check": {
    source: "lucide",
    sourceName: "check",
    viewBox: "0 0 24 24",
    opticalScale: 1,
    opticalX: 0,
    opticalY: 0,
    fill: "none",
    stroke: "currentColor",
    nodes: [
      [
        "path",
        {
          "d": "M20 6 9 17l-5-5"
        }
      ]
    ]
  },
  "chevron-down": {
    source: "lucide",
    sourceName: "chevron-down",
    viewBox: "0 0 24 24",
    opticalScale: 1,
    opticalX: 0,
    opticalY: 0,
    fill: "none",
    stroke: "currentColor",
    nodes: [
      [
        "path",
        {
          "d": "m6 9 6 6 6-6"
        }
      ]
    ]
  },
  "close": {
    source: "lucide",
    sourceName: "x",
    viewBox: "0 0 24 24",
    opticalScale: 1,
    opticalX: 0,
    opticalY: 0,
    fill: "none",
    stroke: "currentColor",
    nodes: [
      [
        "path",
        {
          "d": "M18 6 6 18"
        }
      ],
      [
        "path",
        {
          "d": "m6 6 12 12"
        }
      ]
    ]
  },
  "disclosure": {
    source: "lucide",
    sourceName: "chevron-right",
    viewBox: "0 0 24 24",
    opticalScale: 1,
    opticalX: 0,
    opticalY: 0,
    fill: "none",
    stroke: "currentColor",
    nodes: [
      [
        "path",
        {
          "d": "m9 18 6-6-6-6"
        }
      ]
    ]
  },
  "download": {
    source: "lucide",
    sourceName: "download",
    viewBox: "0 0 24 24",
    opticalScale: 1,
    opticalX: 0,
    opticalY: 0,
    fill: "none",
    stroke: "currentColor",
    nodes: [
      [
        "path",
        {
          "d": "M12 15V3"
        }
      ],
      [
        "path",
        {
          "d": "M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"
        }
      ],
      [
        "path",
        {
          "d": "m7 10 5 5 5-5"
        }
      ]
    ]
  },
  "edit": {
    source: "lucide",
    sourceName: "pencil",
    viewBox: "0 0 24 24",
    opticalScale: 1,
    opticalX: 0,
    opticalY: 0,
    fill: "none",
    stroke: "currentColor",
    nodes: [
      [
        "path",
        {
          "d": "M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z"
        }
      ],
      [
        "path",
        {
          "d": "m15 5 4 4"
        }
      ]
    ]
  },
  "files": {
    source: "lucide",
    sourceName: "folder",
    viewBox: "0 0 24 24",
    opticalScale: 1,
    opticalX: 0,
    opticalY: 0,
    fill: "none",
    stroke: "currentColor",
    nodes: [
      [
        "path",
        {
          "d": "M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z"
        }
      ]
    ]
  },
  "moon": {
    source: "lucide",
    sourceName: "moon",
    viewBox: "0 0 24 24",
    opticalScale: 1,
    opticalX: 0,
    opticalY: 0,
    fill: "none",
    stroke: "currentColor",
    nodes: [
      [
        "path",
        {
          "d": "M20.985 12.486a9 9 0 1 1-9.473-9.472c.405-.022.617.46.402.803a6 6 0 0 0 8.268 8.268c.344-.215.825-.004.803.401"
        }
      ]
    ]
  },
  "next": {
    source: "lucide",
    sourceName: "chevron-right",
    viewBox: "0 0 24 24",
    opticalScale: 1,
    opticalX: 0,
    opticalY: 0,
    fill: "none",
    stroke: "currentColor",
    nodes: [
      [
        "path",
        {
          "d": "m9 18 6-6-6-6"
        }
      ]
    ]
  },
  "open-external": {
    source: "lucide",
    sourceName: "external-link",
    viewBox: "0 0 24 24",
    opticalScale: 1,
    opticalX: 0,
    opticalY: 0,
    fill: "none",
    stroke: "currentColor",
    nodes: [
      [
        "path",
        {
          "d": "M15 3h6v6"
        }
      ],
      [
        "path",
        {
          "d": "M10 14 21 3"
        }
      ],
      [
        "path",
        {
          "d": "M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"
        }
      ]
    ]
  },
  "panel-collapse": {
    source: "lucide",
    sourceName: "panel-left-close",
    viewBox: "0 0 24 24",
    opticalScale: 1,
    opticalX: 0,
    opticalY: 0,
    fill: "none",
    stroke: "currentColor",
    nodes: [
      [
        "rect",
        {
          "width": "18",
          "height": "18",
          "x": "3",
          "y": "3",
          "rx": "2"
        }
      ],
      [
        "path",
        {
          "d": "M9 3v18"
        }
      ],
      [
        "path",
        {
          "d": "m16 15-3-3 3-3"
        }
      ]
    ]
  },
  "panel-expand": {
    source: "lucide",
    sourceName: "panel-left-open",
    viewBox: "0 0 24 24",
    opticalScale: 1,
    opticalX: 0,
    opticalY: 0,
    fill: "none",
    stroke: "currentColor",
    nodes: [
      [
        "rect",
        {
          "width": "18",
          "height": "18",
          "x": "3",
          "y": "3",
          "rx": "2"
        }
      ],
      [
        "path",
        {
          "d": "M9 3v18"
        }
      ],
      [
        "path",
        {
          "d": "m14 9 3 3-3 3"
        }
      ]
    ]
  },
  "previous": {
    source: "lucide",
    sourceName: "chevron-left",
    viewBox: "0 0 24 24",
    opticalScale: 1,
    opticalX: 0,
    opticalY: 0,
    fill: "none",
    stroke: "currentColor",
    nodes: [
      [
        "path",
        {
          "d": "m15 18-6-6 6-6"
        }
      ]
    ]
  },
  "send": {
    source: "lucide",
    sourceName: "send",
    viewBox: "0 0 24 24",
    opticalScale: 1,
    opticalX: 0,
    opticalY: 0,
    fill: "none",
    stroke: "currentColor",
    nodes: [
      [
        "path",
        {
          "d": "M14.536 21.686a.5.5 0 0 0 .937-.024l6.5-19a.496.496 0 0 0-.635-.635l-19 6.5a.5.5 0 0 0-.024.937l7.93 3.18a2 2 0 0 1 1.112 1.11z"
        }
      ],
      [
        "path",
        {
          "d": "m21.854 2.147-10.94 10.939"
        }
      ]
    ]
  },
  "settings": {
    source: "lucide",
    sourceName: "settings",
    viewBox: "0 0 24 24",
    opticalScale: 1,
    opticalX: 0,
    opticalY: 0,
    fill: "none",
    stroke: "currentColor",
    nodes: [
      [
        "path",
        {
          "d": "M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915"
        }
      ],
      [
        "circle",
        {
          "cx": "12",
          "cy": "12",
          "r": "3"
        }
      ]
    ]
  },
  "status-dot": {
    source: "dlightrag",
    sourceName: "status-dot",
    viewBox: "0 0 24 24",
    opticalScale: 1,
    opticalX: 0,
    opticalY: 0,
    fill: "currentColor",
    stroke: "none",
    nodes: [
      [
        "circle",
        {
          "cx": "12",
          "cy": "12",
          "r": "4"
        }
      ]
    ]
  },
  "stop": {
    source: "lucide",
    sourceName: "square",
    viewBox: "0 0 24 24",
    opticalScale: 1,
    opticalX: 0,
    opticalY: 0,
    fill: "currentColor",
    stroke: "none",
    nodes: [
      [
        "rect",
        {
          "width": "18",
          "height": "18",
          "x": "3",
          "y": "3",
          "rx": "2"
        }
      ]
    ]
  },
  "sun": {
    source: "lucide",
    sourceName: "sun",
    viewBox: "0 0 24 24",
    opticalScale: 1,
    opticalX: 0,
    opticalY: 0,
    fill: "none",
    stroke: "currentColor",
    nodes: [
      [
        "circle",
        {
          "cx": "12",
          "cy": "12",
          "r": "4"
        }
      ],
      [
        "path",
        {
          "d": "M12 2v2"
        }
      ],
      [
        "path",
        {
          "d": "M12 20v2"
        }
      ],
      [
        "path",
        {
          "d": "m4.93 4.93 1.41 1.41"
        }
      ],
      [
        "path",
        {
          "d": "m17.66 17.66 1.41 1.41"
        }
      ],
      [
        "path",
        {
          "d": "M2 12h2"
        }
      ],
      [
        "path",
        {
          "d": "M20 12h2"
        }
      ],
      [
        "path",
        {
          "d": "m6.34 17.66-1.41 1.41"
        }
      ],
      [
        "path",
        {
          "d": "m19.07 4.93-1.41 1.41"
        }
      ]
    ]
  },
  "system": {
    source: "lucide",
    sourceName: "monitor",
    viewBox: "0 0 24 24",
    opticalScale: 1,
    opticalX: 0,
    opticalY: 0,
    fill: "none",
    stroke: "currentColor",
    nodes: [
      [
        "rect",
        {
          "width": "20",
          "height": "14",
          "x": "2",
          "y": "3",
          "rx": "2"
        }
      ],
      [
        "line",
        {
          "x1": "8",
          "x2": "16",
          "y1": "21",
          "y2": "21"
        }
      ],
      [
        "line",
        {
          "x1": "12",
          "x2": "12",
          "y1": "17",
          "y2": "21"
        }
      ]
    ]
  }
} as const satisfies Record<string, IconDefinition>;
export type IconName = keyof typeof ICON_REGISTRY;
