# Copyright 2025-2026 Hanlian Lu. SPDX-License-Identifier: Apache-2.0
"""The ``boilerplate`` warning: declarations nobody asked for are flagged, real analysis never is."""

import json
from pathlib import Path

import html_report
import pytest


def hits(markup: str) -> list[str]:
    """The boilerplate warnings of a fragment, as the build prints them."""
    report = html_report._Report(html_report._parse(markup))
    html_report._check_boilerplate(report)
    return report.warnings


@pytest.mark.parametrize(
    ("text", "phrase", "family"),
    [
        ("本报告由 AI 生成，内容仅供读者阅读。", "AI 生成", "an AI or model credit"),
        ("内容为AI生成", "AI生成", "an AI or model credit"),
        ("这份分析由大模型撰写", "由大模型撰写", "an AI or model credit"),
        ("由人工智能生成", "由人工智能生成", "an AI or model credit"),
        ("本报告由数据团队编制", "本报告由数据团队编制", "an AI or model credit"),
        ("This page is AI-generated.", "AI-generated", "an AI or model credit"),
        ("Generated by an LLM.", "Generated by an LLM", "an AI or model credit"),
        ("Written by Claude for you", "Written by Claude", "an AI or model credit"),
        ("以上数据仅供参考。", "仅供参考", "a disclaimer"),
        ("本文仅供学习交流", "仅供学习", "a disclaimer"),
        ("本分析不构成任何投资建议。", "不构成任何投资建议", "a disclaimer"),
        ("免责声明：请自行判断。", "免责声明", "a disclaimer"),
        ("Disclaimer: use at your own risk.", "Disclaimer", "a disclaimer"),
        ("For informational purposes only.", "For informational purposes only", "a disclaimer"),
        ("This is not financial advice.", "not financial advice", "a disclaimer"),
        ("我们重视您的隐私保护。", "隐私保护", "a privacy, compliance or copyright notice"),
        ("隐私政策", "隐私政策", "a privacy, compliance or copyright notice"),
        ("个人信息保护说明", "个人信息保护", "a privacy, compliance or copyright notice"),
        ("This site uses cookies.", "cookies", "a privacy, compliance or copyright notice"),
        ("GDPR compliant", "GDPR", "a privacy, compliance or copyright notice"),
        ("合规声明", "合规声明", "a privacy, compliance or copyright notice"),
        ("Privacy policy", "Privacy policy", "a privacy, compliance or copyright notice"),
        ("版权所有 2024", "版权所有", "a privacy, compliance or copyright notice"),
        ("© 2024 Example", "©", "a privacy, compliance or copyright notice"),
        (
            "All rights reserved.",
            "All rights reserved",
            "a privacy, compliance or copyright notice",
        ),
        ("生成时间：2024-12-31", "生成时间", "a footer credit"),
        ("本页生成于 2024 年", "生成于", "a footer credit"),
        ("Generated on 31 Dec", "Generated on", "a footer credit"),
        ("Powered by Report Kit", "Powered by", "a footer credit"),
        ("Built with care", "Built with", "a footer credit"),
        ("欢迎订阅我们的周报", "欢迎订阅", "a call to action"),
        ("联系我们获取更多", "联系我们", "a call to action"),
        ("Subscribe for weekly updates", "Subscribe", "a call to action"),
    ],
)
def test_each_family_of_boilerplate_is_flagged_with_its_phrase(
    text: str, phrase: str, family: str
) -> None:
    found = hits(f"<footer><p>{text}</p></footer>")

    assert len(found) == 1, found
    assert found[0].startswith("boilerplate: ")
    assert f'"{phrase}"' in found[0] or phrase.lower() in found[0].lower()
    assert f"is {family}" in found[0]
    assert "delete it" in found[0] and "the reader did not ask for it" in found[0]


@pytest.mark.parametrize(
    "text",
    [
        "来源：国家统计局，2024 年 12 月",
        "来源：委托方提供的年度货物贸易数据",
        "Source: National Bureau of Statistics, March 2024",
        "数据截至 2024-12",
        "数据期间 2018–2024 年",
        "As of March 2024, exports were 109 billion US dollars.",
        "方法：以 2023 年为基期，按当年价格计算。",
        "方法与不确定",
        "假设：汇率维持在 7.1，且利率路径与央行 9 月预测一致；若假设不成立，结论需要重算。",
        "局限：样本只覆盖 2018–2024 年，未包含服务贸易。",
        "投资扩张与合规风险并行",
        "2021–2023 年逾 100 名奖学金博士生录取不合规",
        "会后发表联合声明，成立绿色转型投资工作组",
        "本报告由三部分组成：概览、趋势和明细。",
        "Revenue grew while subscription revenue and subscribers held steady.",
        "The built environment accounts for 40% of emissions.",
        "The model is calibrated on 2018–2023 data and generated results are rounded.",
    ],
)
def test_a_source_line_an_as_of_date_the_method_and_the_assumptions_are_never_flagged(
    text: str,
) -> None:
    assert hits(f"<p>{text}</p>") == []


def test_only_the_visible_text_is_scanned_not_scripts_json_or_attributes() -> None:
    markup = (
        '<p title="仅供参考" aria-label="AI生成" data-note="免责声明">正文</p>'
        "<script>const note = '免责声明，仅供参考';</script>"
        '<script type="application/json" id="chart-a">{"option": {"title": {"subtext": "AI生成"}}}</script>'
        "<style>.x::after { content: '版权所有' }</style>"
        "<title>隐私政策</title>"
    )

    assert hits(markup) == []


def test_one_warning_per_hit_and_a_phrase_split_by_inline_markup_is_still_found() -> None:
    found = hits("<p>以上<b>仅供</b>参考。</p><p>另：本页AI生成，亦<b>AI</b>生成。</p>")

    assert len(found) == 3
    assert sum("a disclaimer" in line for line in found) == 1
    assert sum("an AI or model credit" in line for line in found) == 2


def test_the_warning_names_the_line_of_the_phrase() -> None:
    found = hits("<p>正文</p>\n<p>正文</p>\n<p>版权所有</p>")

    assert "(line 3)" in found[0]


def test_the_build_warns_but_does_not_fail(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    fragment = tmp_path / "r.html"
    spec = {
        "option": {
            "title": {"text": "T", "subtext": "S"},
            "dataset": {"source": [{"k": "a", "v": 1}]},
            "xAxis": {"type": "category"},
            "yAxis": {"type": "value"},
            "series": [{"type": "bar", "encode": {"x": "k", "y": "v"}}],
        }
    }
    fragment.write_text(
        '<h1>报告</h1><figure class="chart" data-chart="a"></figure>'
        f'<script type="application/json" id="chart-a">{json.dumps(spec)}</script>'
        "<footer>本报告由 AI 生成，仅供参考。</footer>",
        encoding="utf-8",
    )

    code = html_report.main(["build", str(fragment), str(tmp_path / "o.html")])
    err = capsys.readouterr().err

    assert code == 0
    assert err.count("html-report: warning: boilerplate:") == 2
    assert (tmp_path / "o.html").exists()
